import type {
  ClientConfiguration,
  GeneratedIntelligence,
  IntelligenceRequest
} from '@/lib/qoobix/types';

type CreateMarkdownReportInput = {
  client: ClientConfiguration;
  request: IntelligenceRequest;
  intelligence: GeneratedIntelligence;
};

function clean(value: string | null | undefined, fallback = 'Not supplied') {
  return (value && value.trim() ? value.trim() : fallback)
    .replace(/\bUnverified\b/g, 'Candidate for verification')
    .replace(/\bunverified\b/g, 'candidate for verification');
}

function bulletList(items: string[]) {
  if (!items.length) return '- Not supplied';

  return items.map((item) => `- ${clean(item, '—')}`).join('\n');
}

function candidateCards(
  title: string,
  rows: Array<{
    name: string;
    category?: string;
    type?: string;
    countryOrRegion: string;
    locality?: string;
    region?: string;
    website: string;
    verificationUrl: string;
    relevance: string;
    suggestedAction?: string;
    status: string;
    notes: string;
  }>
) {
  if (!rows.length) {
    return `## ${title}\n\nNo candidate organisations were exported for this section.\n`;
  }

  return [
    `## ${title}`,
    '',
    ...rows.map((row, index) =>
      [
        `### Candidate ${index + 1} — ${clean(row.name, 'Candidate organisation')}`,
        '',
        `**Type:** ${clean(row.category ?? row.type, 'Candidate')}`,
        `**Location:** ${clean([row.locality, row.region, row.countryOrRegion].filter(Boolean).join(', '), 'Not supplied')}`,
        `**Website:** ${clean(row.website, 'Not supplied')}`,
        `**Verification URL:** ${clean(row.verificationUrl, 'Not supplied')}`,
        `**Relevance:** ${clean(row.relevance, 'Requires verification.')}`,
        `**Suggested verification action:** ${clean(row.suggestedAction, 'Check relevance, location, website, category and commercial fit before use.')}`,
        `**Notes:** ${clean(row.notes, 'Candidate organisation for verification.')}`,
        `**Status:** ${clean(row.status, 'Candidate organisation for verification')}`,
        '',
        '---',
        ''
      ].join('\n')
    )
  ].join('\n');
}

export function createMarkdownReport(input: CreateMarkdownReportInput): Buffer {
  const { client, request, intelligence } = input;

  const markdown = [
    '# QOOBIX IDAAS Market Intelligence Report',
    '',
    '**Generated by:** QOOBIX IDAAS / Proteus',
    `**Generated:** ${new Date().toLocaleDateString('en-GB')}`,
    `**Operator workspace:** ${clean(client.name, 'Authorised operator')}`,
    `**Product/service analysed:** ${clean(request.productOrService)}`,
    `**Target country/countries:** ${clean(request.targetCountries)}`,
    `**Target geography:** ${clean(request.targetGeography)}`,
    `**Commercial objective:** ${clean(request.commercialObjective)}`,
    `**Report language:** ${clean(request.preferredOutputLanguage)}`,
    '',
    '> AI-assisted, operator-reviewed market intelligence. Named organisations and market claims require verification before commercial use.',
    '',
    '## Decision brief',
    '',
    clean(intelligence.executiveSummary, 'No executive summary generated.'),
    '',
    '## Client and product context',
    '',
    clean(intelligence.clientProductContext, 'No product context generated.'),
    '',
    '## Target market overview',
    '',
    clean(intelligence.targetMarketOverview, 'No target market overview generated.'),
    '',
    '## Demand signals to investigate',
    '',
    bulletList(intelligence.demandSignals),
    '',
    '## Channel opportunities',
    '',
    bulletList(intelligence.channelOpportunities),
    '',
    candidateCards('Candidate organisations for verification', intelligence.potentialPartnersProspects),
    '',
    candidateCards('Competitor, substitute and alternative landscape', intelligence.competitorRows),
    '',
    '## Competitor and substitute notes',
    '',
    bulletList(intelligence.competitorsAlternatives),
    '',
    '## Regional or segment priorities',
    '',
    bulletList(intelligence.regionalPriorities),
    '',
    '## Positioning recommendations',
    '',
    bulletList(intelligence.positioningRecommendations),
    '',
    '## Risks and caveats',
    '',
    bulletList(intelligence.commercialRisks),
    '',
    '## Action matrix',
    '',
    '| Priority | Action | Verification / next evidence |',
    '|---:|---|---|',
    ...(intelligence.actionPriorities.length
      ? intelligence.actionPriorities.map(
          (action, index) =>
            `| ${index + 1} | ${clean(action, 'Action required').replace(/\|/g, '\\|')} | Check source evidence, buyer/channel feedback, direct market signals or internal feasibility. |`
        )
      : ['| 1 | Define next action. | Manual review required. |']),
    '',
    '## Verification workflow',
    '',
    bulletList(intelligence.sourceNotesLimitations),
    '',
    '## Final verification notice',
    '',
    'This report is AI-assisted and may contain incomplete, outdated or candidate information requiring review. Named entities, websites, market claims, competitor references, regulatory assumptions and commercial recommendations must be checked before use. QOOBIX IDAAS does not replace professional judgement, source checking, commercial due diligence, legal advice, financial advice, technical assessment or regulatory review.'
  ].join('\n');

  return Buffer.from(markdown, 'utf8');
}
