import type {
  ClientConfiguration,
  GeneratedIntelligence,
  IntelligenceRequest
} from '@/lib/qoobix/types';

type CreateRtfReportInput = {
  client: ClientConfiguration;
  request: IntelligenceRequest;
  intelligence: GeneratedIntelligence;
};

function cleanOutput(value: string | null | undefined) {
  return (value && value.trim() ? value : '—')
    .replace(/\bUnverified\b/g, 'Candidate for verification')
    .replace(/\bunverified\b/g, 'candidate for verification');
}

function rtfEscape(value: string | null | undefined) {
  const text = cleanOutput(value);

  return text
    .replaceAll('\\', '\\\\')
    .replaceAll('{', '\\{')
    .replaceAll('}', '\\}')
    .replace(/\n/g, '\\par ')
    .replace(/[^\x00-\x7F]/g, (character) => {
      const code = character.charCodeAt(0);

      return `\\u${code}?`;
    });
}

function line(text = '') {
  return `${rtfEscape(text)}\\par\n`;
}

function title(text: string) {
  return `\\fs36\\b ${rtfEscape(text)}\\b0\\fs24\\par\n`;
}

function heading(text: string) {
  return `\\par\\fs30\\b ${rtfEscape(text)}\\b0\\fs24\\par\n`;
}

function subheading(text: string) {
  return `\\par\\fs26\\b ${rtfEscape(text)}\\b0\\fs24\\par\n`;
}

function labelValue(label: string, value: string) {
  return `\\b ${rtfEscape(label)}:\\b0 ${rtfEscape(value)}\\par\n`;
}

function verificationRoute(value: string | null | undefined) {
  const url = value && value.trim() ? value.trim() : '';

  if (!url) {
    return labelValue('Verification route', 'Not supplied');
  }

  return labelValue('Verification route', url);
}

function bulletList(items: string[]) {
  if (!items.length) {
    return line('—');
  }

  return items.map((item) => `\\bullet\\tab ${rtfEscape(item)}\\par\n`).join('');
}

function partnerBlocks(intelligence: GeneratedIntelligence) {
  if (!intelligence.potentialPartnersProspects.length) {
    return line('No structured partner/prospect rows were generated.');
  }

  return intelligence.potentialPartnersProspects
    .map(
      (item, index) =>
        `${subheading(`${index + 1}. ${item.name}`)}${labelValue('Type', item.category)}${labelValue(
          'Country/region',
          item.countryOrRegion
        )}${labelValue('Status', item.status || 'Candidate for verification')}${verificationRoute(
          item.verificationUrl
        )}${labelValue('Relevance', item.relevance)}${labelValue(
          'Suggested action',
          item.suggestedAction
        )}${labelValue('Notes', item.notes)}`
    )
    .join('');
}

function competitorBlocks(intelligence: GeneratedIntelligence) {
  if (!intelligence.competitorRows.length) {
    return line('No structured competitor/alternative rows were generated.');
  }

  return intelligence.competitorRows
    .map(
      (item, index) =>
        `${subheading(`${index + 1}. ${item.name}`)}${labelValue('Type', item.type)}${labelValue(
          'Country/region',
          item.countryOrRegion
        )}${labelValue('Status', item.status || 'Candidate for verification')}${verificationRoute(
          item.verificationUrl
        )}${labelValue('Relevance', item.relevance)}${labelValue('Notes', item.notes)}`
    )
    .join('');
}

function actionBlocks(actions: string[]) {
  if (!actions.length) {
    return line('—');
  }

  return actions
    .map(
      (action, index) =>
        `${subheading(`Action ${index + 1}`)}${line(action)}${labelValue(
          'Purpose',
          'Turn the intelligence into a practical commercial step.'
        )}${labelValue(
          'Verification / next evidence',
          'Confirm with direct source checks, market evidence, buyer/channel feedback, or internal review.'
        )}`
    )
    .join('');
}

function verificationBlocks(notes: string[]) {
  if (!notes.length) {
    return line('No specific source or verification notes were generated.');
  }

  return notes
    .map(
      (note, index) =>
        `${subheading(`Verification item ${index + 1}`)}${labelValue(
          'Area to verify',
          note
        )}${labelValue(
          'Why it matters',
          'Reduces the risk of acting on incomplete or uncertain intelligence.'
        )}${labelValue(
          'Suggested verification action',
          'Check primary sources, official directories, trade bodies, buyer feedback, distributor confirmation, or direct outreach.'
        )}`
    )
    .join('');
}

export function createRtfReport(input: CreateRtfReportInput): Buffer {
  const { client, request, intelligence } = input;

  const body = [
    title('QOOBIX Market Intelligence Report'),
    line('Generated by QOOBIX · Managed by Proteus'),
    line(
      'AI-assisted market intelligence. Check all outputs before commercial, legal, regulatory, technical, financial, or strategic use.'
    ),

    heading('Report summary'),
    labelValue('Client', client.name),
    labelValue('Sector', client.sector),
    labelValue('Product/service analysed', request.productOrService),
    labelValue('Target country/countries', request.targetCountries),
    labelValue('Commercial objective', request.commercialObjective),
    labelValue('Market question', request.marketQuestion),
    labelValue('Generated', new Date().toLocaleDateString('en-GB')),
    labelValue(
      'Report retention',
      `${client.fileRetentionDays} day(s), unless cleaned earlier after expiry`
    ),

    heading('1. Decision brief'),
    line(intelligence.executiveSummary),

    heading('2. Client and product context'),
    line(intelligence.clientProductContext),

    heading('3. Target market overview'),
    line(intelligence.targetMarketOverview),

    heading('4. Demand signals to investigate'),
    bulletList(intelligence.demandSignals),

    heading('5. Channel opportunities'),
    bulletList(intelligence.channelOpportunities),

    heading('6. Potential partners, prospects, or useful market entry points'),
    partnerBlocks(intelligence),

    heading('7. Competitor, substitute, and alternative landscape'),
    competitorBlocks(intelligence),

    heading('8. Competitor and substitute notes'),
    bulletList(intelligence.competitorsAlternatives),

    heading('9. Regional or segment priorities'),
    bulletList(intelligence.regionalPriorities),

    heading('10. Positioning recommendations'),
    bulletList(intelligence.positioningRecommendations),

    heading('11. Commercial risks and caveats'),
    bulletList(intelligence.commercialRisks),

    heading('12. Action matrix'),
    actionBlocks(intelligence.actionPriorities),

    heading('13. Verification workflow'),
    verificationBlocks(intelligence.sourceNotesLimitations),

    heading('Final verification notice'),
    line(
      'This report is AI-assisted and may contain incomplete, outdated, or candidate information requiring review. Named entities, market claims, competitor references, regulatory assumptions, and commercial recommendations must be checked before use. QOOBIX does not replace professional judgement, source checking, commercial due diligence, legal advice, financial advice, technical assessment, or regulatory review.'
    )
  ].join('');

  const rtf = `{\\rtf1\\ansi\\deff0
{\\fonttbl{\\f0 Arial;}}
\\f0\\fs24
${body}
}`;

  return Buffer.from(rtf, 'utf8');
}
